
/EkfCalNode:
    ros__parameters:
        IMU_list:
            - vn300

        Camera_list:
            - ace

        IMU:
            vn300:
                BaseSensor: True
                Intrinsic: False
                Rate: 400.0
                Topic: "/vn300/imu_uncompensated"

        Camera:
            ace:
                Rate: 40.0
                Topic:  "/my_camera/pylon_ros2_camera_node/image_raw"
                PosOffInit:  [0.0, 0.0, 0.0]
                AngOffInit: [1.0, 0.0, 0.0, 0.0]
                VarInit: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
