
/EkfCalNode:
    ros__parameters:
        IMU_list:
            - vn300
            - vn100

        Camera_list:
            - dummy_cam_1
            - dummy_cam_2

        LIDAR_list:
            - dummy_lidar_1
            - dummy_lidar_2


        IMUs:
            vn300:
                Intrinsic: False
                Rate: 400.0
                Topic:
                PosOffInit:  [0.0, 0.0, 0.0]
                QuatOffInit: [1.0, 0.0, 0.0, 0.0]
                AccBiasInit: [0.0, 0.0, 0.0]
                OmgBiasInit: [0.0, 0.0, 0.0]

            vn100:
                Intrinsic: True
                Rate: 100.0
                Topic:
                PosOffInit:  [0.0, 0.0, 0.0]
                QuatOffInit: [1.0, 0.0, 0.0, 0.0]
                AccBiasInit: [0.0, 0.0, 0.0]
                OmgBiasInit: [0.0, 0.0, 0.0]


        Cameras:
            dummy_cam_1:
                Rate: 1.0
                Topic: 
                PosOffInit:  [0.0, 0.0, 0.0]
                QuatOffInit: [1.0, 0.0, 0.0, 0.0]

            dummy_cam_2:
                Rate: 1.0
                Topic: 
                PosOffInit:  [0.0, 0.0, 0.0]
                QuatOffInit: [1.0, 0.0, 0.0, 0.0]


        LIDARs:
            dummy_lidar_1:
                Rate: 1.0
                Topic: 
                PosOffInit:  [0.0, 0.0, 0.0]
                QuatOffInit: [1.0, 0.0, 0.0, 0.0]

            dummy_lidar_2:
                Rate: 1.0
                Topic: 
                PosOffInit:  [0.0, 0.0, 0.0]
                QuatOffInit: [1.0, 0.0, 0.0, 0.0]

